/**
 * Label maps for zone classification
 * Maps numeric codes to human-readable zone names
 */

const labelMap_hlzIII = {
  111: 'Tropical Rain Forest',
  112: 'Tropical Wet Forest',
  113: 'Tropical Moist Forest',
  114: 'Tropical Dry Forest',
  115: 'Tropical Very Dry Forest',
  116: 'Tropical Thorn Woodland',
  117: 'Tropical Desert Scrub',
  118: 'Tropical Desert',
  121: 'Tropical Premontane Rain Forest',
  122: 'Tropical Premontane Wet Forest',
  123: 'Tropical Premontane Moist Forest',
  124: 'Tropical Premontane Dry Forest',
  125: 'Tropical Premontane Thorn Woodland',
  126: 'Tropical Premontane Desert Scrub',
  127: 'Tropical Premontane Desert',
  131: 'Tropical Lower Montane Rain Forest',
  132: 'Tropical Lower Montane Wet Forest',
  133: 'Tropical Lower Montane Moist Forest',
  134: 'Tropical Lower Montane Dry Forest',
  135: 'Tropical Lower Montane Thorn Woodland',
  136: 'Tropical Lower Montane Desert Scrub',
  137: 'Tropical Lower Montane Desert',
  141: 'Tropical Montane Rain Forest',
  142: 'Tropical Montane Wet Forest',
  143: 'Tropical Montane Moist Forest',
  144: 'Tropical Montane Steppe',
  145: 'Tropical Montane Desert Scrub',
  146: 'Tropical Montane Desert',
  151: 'Tropical Subalpine Rain Forest',
  152: 'Tropical Subalpine Wet Forest',
  153: 'Tropical Subalpine Moist Forest',
  154: 'Tropical Subalpine Dry Scrub',
  155: 'Tropical Subalpine Desert',
  161: 'Tropical Alpine Rain Tundra',
  162: 'Tropical Alpine Wet Tundra',
  163: 'Tropical Alpine Moist Tundra',
  164: 'Tropical Alpine Desert',
  171: 'Tropical Nival Desert',
  211: 'Subtropical Rain Forest',
  212: 'Subtropical Wet Forest',
  213: 'Subtropical Moist Forest',
  214: 'Subtropical Dry Forest',
  215: 'Subtropical Thorn Woodland',
  216: 'Subtropical Desert Scrub',
  217: 'Subtropical Desert',
  221: 'Subtropical Lower Montane Rain Forest',
  222: 'Subtropical Lower Montane Wet Forest',
  223: 'Subtropical Lower Montane Moist Forest',
  224: 'Subtropical Lower Montane Dry Forest',
  225: 'Subtropical Lower Montane Thorn Woodland',
  226: 'Subtropical Lower Montane Desert Scrub',
  227: 'Subtropical Lower Montane Desert',
  231: 'Subtropical Montane Rain Forest',
  232: 'Subtropical Montane Wet Forest',
  233: 'Subtropical Montane Moist Forest',
  234: 'Subtropical Montane Steppe',
  235: 'Subtropical Montane Desert Scrub',
  236: 'Subtropical Montane Desert',
  241: 'Subtropical Subalpine Rain Forest',
  242: 'Subtropical Subalpine Wet Forest',
  243: 'Subtropical Subalpine Moist Forest',
  244: 'Subtropical Subalpine Dry Scrub',
  245: 'Subtropical Subalpine Desert',
  251: 'Subtropical Alpine Rain Tundra',
  252: 'Subtropical Alpine Wet Tundra',
  253: 'Subtropical Alpine Moist Tundra',
  254: 'Subtropical Alpine Desert',
  261: 'Subtropical Nival Desert',
  311: 'Warm Temperate Rain Forest',
  312: 'Warm Temperate Wet Forest',
  313: 'Warm Temperate Moist Forest',
  314: 'Warm Temperate Dry Forest',
  315: 'Warm Temperate Thorn Woodland',
  316: 'Warm Temperate Desert Scrub',
  317: 'Warm Temperate Desert',
  321: 'Warm Temperate Montane Rain Forest',
  322: 'Warm Temperate Montane Wet Forest',
  323: 'Warm Temperate Montane Moist Forest',
  324: 'Warm Temperate Montane Steppe',
  325: 'Warm Temperate Montane Desert Scrub',
  326: 'Warm Temperate Montane Desert',
  331: 'Warm Temperate Subalpine Rain Forest',
  332: 'Warm Temperate Subalpine Wet Forest',
  333: 'Warm Temperate Subalpine Moist Forest',
  334: 'Warm Temperate Subalpine Dry Scrub',
  335: 'Warm Temperate Subalpine Desert',
  341: 'Warm Temperate Alpine Rain Tundra',
  342: 'Warm Temperate Alpine Wet Tundra',
  343: 'Warm Temperate Alpine Moist Tundra',
  344: 'Warm Temperate Alpine Desert',
  351: 'Warm Temperate Nival Desert',
  411: 'Cool Temperate Rain Forest',
  412: 'Cool Temperate Wet Forest',
  413: 'Cool Temperate Moist Forest',
  414: 'Cool Temperate Steppe',
  415: 'Cool Temperate Desert Scrub',
  416: 'Cool Temperate Desert',
  421: 'Cool Temperate Subalpine Rain Forest',
  422: 'Cool Temperate Subalpine Wet Forest',
  423: 'Cool Temperate Subalpine Moist Forest',
  424: 'Cool Temperate Subalpine Dry Scrub',
  425: 'Cool Temperate Subalpine Desert',
  431: 'Cool Temperate Alpine Rain Tundra',
  432: 'Cool Temperate Alpine Wet Tundra',
  433: 'Cool Temperate Alpine Moist Tundra',
  434: 'Cool Temperate Alpine Desert',
  441: 'Cool Temperate Nival Desert',
  511: 'Boreal Rain Forest',
  512: 'Boreal Wet Forest',
  513: 'Boreal Moist Forest',
  514: 'Boreal Dry Scrub',
  515: 'Boreal Desert',
  521: 'Boreal Alpine Rain Tundra',
  522: 'Boreal Alpine Wet Tundra',
  523: 'Boreal Alpine Moist Tundra',
  524: 'Boreal Alpine Desert',
  531: 'Boreal Nival Desert',
  611: 'Subpolar Rain Tundra',
  612: 'Subpolar Wet Tundra',
  613: 'Subpolar Moist Tundra',
  614: 'Subpolar Desert',
  621: 'Subpolar Nival Desert',
  711: 'Polar'
};

const labelMap_hlzII = {
  11: "Tropical Rain Forest",
  12: "Tropical Wet Forest",
  13: "Tropical Moist Forest",
  14: "Tropical Dry Forest",
  15: "Tropical Very Dry Forest",
  16: "Tropical Thorn Woodland",
  17: "Tropical Desert Scrub",
  18: "Tropical Desert",
  21: "Subtropical Rain Forest",
  22: "Subtropical Wet Forest",
  23: "Subtropical Moist Forest",
  24: "Subtropical Dry Forest",
  25: "Subtropical Thorn Woodland",
  26: "Subtropical Desert Scrub",
  27: "Subtropical Desert",
  31: "Warm Temperate Rain Forest",
  32: "Warm Temperate Wet Forest",
  33: "Warm Temperate Moist Forest",
  34: "Warm Temperate Dry Forest",
  35: "Warm Temperate Thorn Woodland",
  36: "Warm Temperate Desert Scrub",
  37: "Warm Temperate Desert",
  41: "Cool Temperate Rain Forest",
  42: "Cool Temperate Wet Forest",
  43: "Cool Temperate Moist Forest",
  44: "Cool Temperate Steppe",
  45: "Cool Temperate Desert Scrub",
  46: "Cool Temperate Desert",
  51: "Boreal Rain Forest",
  52: "Boreal Wet Forest",
  53: "Boreal Moist Forest",
  54: "Boreal Dry Scrub",
  55: "Boreal Desert",
  61: "Subpolar Rain Tundra",
  62: "Subpolar Wet Tundra",
  63: "Subpolar Moist Tundra",
  64: "Subpolar Dry Tundra",
  71: "Polar",
};

const labelMap_gez = {
  11: 'Tropical Rain Forest',
  12: 'Tropical Moist Forest',
  13: 'Tropical Dry Forest',
  14: 'Tropical Shrubland',
  15: 'Tropical Desert',
  21: 'Subtropical Rain Forest',
  22: 'Subtropical Moist Forest',
  23: 'Subtropical Dry Forest',
  24: 'Subtropical Shrubland',
  25: 'Subtropical Desert',
  31: 'Warm Temperate Rain Forest',
  32: 'Warm Temperate Moist Forest',
  33: 'Warm Temperate Dry Forest',
  34: 'Warm Temperate Shrubland',
  35: 'Warm Temperate Desert',
  41: 'Cool Temperate Rain/Wet Forest',
  42: 'Cool Temperate Moist Forest',
  43: 'Cool Temperate Steppe',
  44: 'Cool Temperate Desert',
  51: 'Boreal Rain/Wet Forest',
  52: 'Boreal Moist Forest',
  53: 'Boreal Dry Scrub',
  54: 'Boreal Desert',
  61: 'Subpolar Rain/Wet Tundra',
  62: 'Subpolar Moist Tundra',
  63: 'Subpolar Dry Tundra',
  71: 'Polar'
};

const labelMap_gcz = {
  1: 'Tropical Wet',
  2: 'Tropical Moist',
  3: 'Tropical Dry',
  4: 'Warm Temperate Moist',
  5: 'Warm Temperate Dry',
  6: 'Cool Temperate Moist',
  7: 'Cool Temperate Dry',
  8: 'Boreal Moist',
  9: 'Boreal Dry',
  10: 'Polar'
};

const labelMap_soil = {
  1: 'HAC',
  2: 'LAC',
  3: 'Sandy soils',
  4: 'Spodic',
  5: 'Volcanic soils',
  6: 'Wetland soils',
  7: 'Organic',
  8: 'Water'
};

/**
 * Convert GEZ numeric value to formatted code (e.g., 11 -> '1a')
 */
function formatGEZCode(value) {
  if (value === null || value === undefined) return 'No data';
  // Return the original numeric GEZ code as a string (e.g., 11, 12, 13)
  return String(value);
}

module.exports = {
  labelMap_hlzIII,
  labelMap_hlzII,
  labelMap_gez,
  labelMap_gcz,
  labelMap_soil,
  formatGEZCode,
};
